### ISSUE TITLE
BR: Make sure all the tables & API endpoints are implemented as per specification

### ISSUE THREAD

**Issue by sarafalamaki** [data61/Mirza#214]
The spec can be found here.

https://confluence.csiro.au/display/blockchaintechnology/Business+Registry+Service+Architecture

TODO:
- [x] Add Location table (#238)
- [ ] ~Add last updated fields~ (Moved to #254)
- [ ] ~Add last updated triggers?~ (Moved to #254)
- [ ] ~Add metadata table?~
- [x] #209 Record who revoked the key.

_Original Author: fal05c_

_(Moved with github-migration-0.1.0.0 (package github-migration-0.1.0.0 revision df9f38b))_
